export default {
  title: 'Editor',
  information: 'Information',
  panelDistance: 'Distance between Solar Panels (CM)',
  innerMargin: 'Roof inner Margin',
  totalPower: 'Total Power {{power}} kW',
  innerMarginTop: 'Top (CM)',
  innerMarginRight: 'Right (CM)',
  innerMarginBottom: 'Bottom (CM)',
  innerMarginLeft: 'Left (CM)',
  panelPlacement: 'Initial panel placement',
  regenerate: 'Regenerate',
  autoFill: 'Automatic fillment',
  placementHorizontal: 'Horizontal placement',
  placementVertical: 'Vertical placement',
  totalPanels: '%s solar panels.',
  opacity: 'Change transparency',
  horizontalLeft: 'Left',
  horizontalRight: 'Right',
  verticalTop: 'Top',
  center: 'Center',
  verticalBottom: 'Bottom',
  addNewPanel: 'Add new Solar Panel',
};
