export default {
    editor: 'Editor',
    information: 'Information',
    panelDistance: 'Distance between Solar Panels (CM)',
    innerMargin: 'Roof inner Margin',
    innerMarginTop: 'Top (CM)',
    innerMarginRight: 'Right (CM)',
    innerMarginBottom: 'Bottom (CM)',
    innerMarginLeft: 'Left (CM)',
    panelPlacement: 'Initial panel placement',
    regenerate: 'Regenerate',
    autoFill: 'Automatic fillment',
    placementHorizontal: 'Horizontal placement',
    placementVertical: 'Vertical placement',
}