export default {
  title: 'Users',
  add_user: 'Add User',
  edit_user: 'Edit User',
  firstName: 'Fist name',
  lastName: 'Last name',
  birthDate: 'Date of birth',
  place_of_residence: 'Place of residence',
  street: 'Street',
  stree_number: 'Number',
  zip_code: 'Zip Code',
  notes: 'Notes',
  email: 'E-Mail',
  phone_number: 'Phone Number',
  personal_data: 'Personal Data',
  contacting_information: 'Contacting Information',
  address_data: 'Address data',
  no_data:
    'There is not yet a User configured.\nPlease add a User to continue.',
  add_user_success: 'User added succesfully!',
  edit_user_success: 'The user was edited successfully!',
  delete_user_title: 'Delete User?',
  delete_user_prompt: 'Are you sure that you want to delte the user {{user}}?',
};
