export default {
  title: 'Editor',
  information: 'Information',
  panelDistance: 'Abstand zwischen den Solar Panels (CM)',
  innerMargin: 'Abstand vom Dach zu den Panels',
  innerMarginTop: 'Oben (CM)',
  innerMarginRight: 'Rechts (CM)',
  innerMarginBottom: 'Unten (CM)',
  innerMarginLeft: 'Links (CM)',
  panelPlacement: 'Solar Panels Ausrichtung',
  regenerate: 'Neu platzieren',
  autoFill: 'Automatische Befüllung',
  placementHorizontal: 'Horizontale Ausrichtung',
  placementVertical: 'Vertikale Ausrichtung',
  totalPanels: 'Es sind ingessamt %s Solar Panels platziert',
  opacity: 'Transaparenz Einstellen',
  horizontalLeft: 'Links',
  horizontalRight: 'Rechts',
  verticalTop: 'Oben',
  center: 'Mittig',
  verticalBottom: 'Unten',
  addNewPanel: 'Solar Modul hinzufügen',
};
