export default {
  title: 'Benutzer',
  add_user: 'Benutzer hinzufügen',
  select_user: 'Benutzer auswählen',
  edit_user: 'Benutzer editieren',
  firstName: 'Vorname',
  lastName: 'Nachname',
  birthDate: 'Geburtstag',
  place_of_residence: 'Wohnort',
  street: 'Strasse',
  street_number: 'Nummer',
  zip_code: 'Postleitzahl',
  notes: 'Notizen',
  email: 'E-Mail',
  phone_number: 'Telefon Nummer',
  personal_data: 'Persönliche Daten',
  contacting_information: 'Kontatktinformationen',
  address_data: 'Address Daten',
  no_data:
    'Es wurde noch kein Benutzer erstellt.\nBitte erstellen Sie einen um weiter zu gehen.',
  add_user_success: 'Der Benutzer wurde hinzugefügt!',
  edit_user_success: 'Der Benutzer wurde bearbeitet!',
  delete_user_title: 'Benutzer löschen',
  delete_user_prompt:
    'Sind sie sicher das Sie den Benutzer {{user}} löschen möchten?',
};
